#
# Apache configuration example for OpenID Connect authentication
#
# To use it:
#
# - Create an Epigraf user with the username set to a claim value that will be passed by your authentication provider.
# - In the app.php, set Logins.remote to the environment variable that will contain the authenticated username,
#   e.g. 'REDIRECT_OIDC_CLAIM_email'.
# - Adjust the OIDC settings below. Make sure the scopes include the claim you want to use as username.
# - Add the content of this file to your Apache config. See the comments in Dockerfile.
# - Check rewrite rules in htdocs/.htaccess and make sure the redirect callback /users/oidc is handled by Apache, not Epigraf.

LoadModule auth_openidc_module modules/mod_auth_openidc.so

# Configure OpenID Connect parameters
OIDCProviderMetadataURL https://YOURPROVIDERDOMAIN/.well-known/openid-configuration
OIDCClientID epigraf-app
OIDCClientSecret YOURVERYSECRETSECRET
OIDCRedirectURI https://YOURSERVERDOMAIN/users/oidc
OIDCCryptoPassphrase the-super-secret-passphrase
OIDCScope "openid email profile"

# Protect the login endpoint and the redirect callback with oidc
# TODO: A call to /users/logout clears the Epigraf session.
#       How to clear the oidc session as well?
#       As a workaround, maybe configure calls of /users/login to always re-authenticate?
<Location /users/login >
    AuthType openid-connect
    Require valid-user
</Location>

<Location /users/oidc >
    AuthType openid-connect
    Require valid-user
</Location>
