graph LR
    Projects --> Articles
    Articles --> Sections
    Sections --> Items
    Items --> Properties
    Items --> Links
    Links --> Properties
    Items --> Footnotes
    Footnotes --> Links
