<?php 
 return array (
  0 => 
  array (
    'id' => 1,
    'deleted' => 0,
    'version_id' => NULL,
    'job_id' => 3,
    'published' => NULL,
    'created' => 
    \Cake\I18n\FrozenTime::__set_state(array(
       'date' => '2008-05-05 18:51:24.000000',
       'timezone_type' => 3,
       'timezone' => 'Europe/Berlin',
    )),
    'created_by' => NULL,
    'modified_by' => 5,
    'sortno' => 26,
    'sortkey' => 'HolzPublic',
    'propertytype' => 'materials',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'HolzPublic',
    'name' => 'HolzPublic',
    'unit' => NULL,
    'comment' => 'Do some wooden comments arrive from the public database?',
    'content' => NULL,
    'elements' => NULL,
    'keywords' => '',
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => NULL,
    'norm_data' => NULL,
    'norm_iri' => 'holz',
    'import_db' => NULL,
    'import_id' => NULL,
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => 0,
    'lft' => 7,
    'rght' => 8,
  ),
  1 => 
  array (
    'id' => 2,
    'deleted' => 0,
    'version_id' => NULL,
    'job_id' => NULL,
    'published' => NULL,
    'created' => 
    \Cake\I18n\FrozenTime::__set_state(array(
       'date' => '2008-05-05 18:51:24.000000',
       'timezone_type' => 3,
       'timezone' => 'Europe/Berlin',
    )),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => 1,
    'sortkey' => 'ProjectsSortUnknownMaterial',
    'propertytype' => 'materials',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'ProjectsLemmaUnknownMaterial',
    'name' => 'ProjectsNameUnknownMaterial',
    'unit' => NULL,
    'comment' => NULL,
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => NULL,
    'norm_data' => NULL,
    'norm_iri' => NULL,
    'import_db' => NULL,
    'import_id' => NULL,
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => 0,
    'lft' => 1,
    'rght' => 2,
  ),
  2 => 
  array (
    'id' => 3,
    'deleted' => 0,
    'version_id' => NULL,
    'job_id' => 3,
    'published' => NULL,
    'created' => 
    \Cake\I18n\FrozenTime::__set_state(array(
       'date' => '2008-05-05 18:51:24.000000',
       'timezone_type' => 3,
       'timezone' => 'Europe/Berlin',
    )),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => 2,
    'sortkey' => 'PublicSortKnownMaterial',
    'propertytype' => 'materials',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'PublicLemmaKnownMaterial',
    'name' => 'PublicNameKnownMaterial',
    'unit' => NULL,
    'comment' => NULL,
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => NULL,
    'norm_data' => NULL,
    'norm_iri' => 'knownmaterial',
    'import_db' => NULL,
    'import_id' => NULL,
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => 0,
    'lft' => 5,
    'rght' => 6,
  ),
  3 => 
  array (
    'id' => 4,
    'deleted' => 0,
    'version_id' => NULL,
    'job_id' => 3,
    'published' => NULL,
    'created' => 
    \Cake\I18n\FrozenTime::__set_state(array(
       'date' => '2008-05-05 18:51:24.000000',
       'timezone_type' => 3,
       'timezone' => 'Europe/Berlin',
    )),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => 1,
    'sortkey' => 'PublicSortUnknownMaterial',
    'propertytype' => 'materials',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'PublicLemmaUnknownMaterial',
    'name' => 'PublicNameUnknownMaterial',
    'unit' => NULL,
    'comment' => NULL,
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => NULL,
    'norm_data' => NULL,
    'norm_iri' => 'public~2',
    'import_db' => NULL,
    'import_id' => NULL,
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => 0,
    'lft' => 3,
    'rght' => 4,
  ),
); 
?>