<?php 
 return array (
  'id' => 119,
  'deleted' => 0,
  'version_id' => NULL,
  'job_id' => NULL,
  'published' => NULL,
  'created' => '2021-06-14 14:54:36',
  'modified' => '2020-10-29 13:00:58',
  'created_by' => 1,
  'modified_by' => 4,
  'sortno' => 7,
  'sortkey' => 'Schriftart 2',
  'propertytype' => 'fonttypes',
  'signature' => NULL,
  'file_name' => NULL,
  'properties_id' => NULL,
  'lemma' => 'FontLemma',
  'name' => 'FontName',
  'unit' => 'Schriftart 2 Einheit',
  'comment' => 'FontComment',
  'content' => NULL,
  'elements' => NULL,
  'keywords' => 'Schriftart,Font',
  'source_from' => NULL,
  'ishidden' => 0,
  'iscategory' => 0,
  'norm_type' => NULL,
  'norm_data' => 'Schriftart 2 Norm',
  'norm_iri' => NULL,
  'import_db' => 'EX DB Schriftart 2',
  'import_id' => 'Schriftart 2 ID',
  'related_id' => NULL,
  'mergedto_id' => NULL,
  'splitfrom_id' => NULL,
  'parent_id' => NULL,
  'level' => 0,
  'lft' => 7,
  'rght' => 12,
); 
?>