<?php

return array (
  0 =>
  array (
    'id' => '11078',
    'deleted' => '0',
    'published' => NULL,
    'created' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'modified' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => NULL,
    'sortkey' => NULL,
    'propertytype' => 'personnames',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'Martin († 1590)',
    'name' => 'Völschow, Martin († 1590)',
    'unit' => NULL,
    'comment' => 'geboren:gestorben: 1590Vater: Völschow, Martin I (+1546)Mutter: Hundesteden, Gertrud (+)Gatten: 1.Beckmann, Elisabeth 2.Engelbrecht, ReginaVita: Ratsherr in Greifswald 1561-1590, Mitstifter der Marienkanzel {2}Seine Witwe Regina Engelbrecht kaufte am 2. April 1590 die Grabplattte mit der Nr. 7  in der Nikolaikirche, unter der Martin und später sie selbst bestattet wurden.',
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => 'doida',
    'norm_data' => 'doida:13',
    'norm_iri' => NULL,
    'import_db' => 'personen.mdb',
    'import_id' => '385',
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => '0',
    'lft' => '1',
    'rght' => '2',

  ),
  1 =>
  array (
    'id' => '23919',
    'deleted' => '0',
    'published' => NULL,
    'created' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'modified' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => NULL,
    'sortkey' => NULL,
    'propertytype' => 'personnames',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'Daniel',
    'name' => 'Völschow, Daniel',
    'unit' => NULL,
    'comment' => 'geboren:gestorben:Vater: Völschow, Martin II (+1590)Mutter: Engelbrecht, Regina (+)Gatten: 1.Bünsow, MargaretheVita: 1601 Greifswalder Bürger {3}',
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => 'doida',
    'norm_data' => 'doida:14',
    'norm_iri' => NULL,
    'import_db' => '',
    'import_id' => '',
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => '0',
    'lft' => '3',
    'rght' => '4',

  ),
  2 =>
  array (
    'id' => '23920',
    'deleted' => '0',
    'published' => NULL,
    'created' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'modified' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => NULL,
    'sortkey' => NULL,
    'propertytype' => 'personnames',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'Evalina',
    'name' => 'Völschow, Evalina',
    'unit' => NULL,
    'comment' => 'nie gestorben',
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => 'doida',
    'norm_data' => '',
    'norm_iri' => NULL,
    'import_db' => 'fiktiv.mdb',
    'import_id' => '1',
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => '0',
    'lft' => '5',
    'rght' => '6',

  ),
  3 =>
  array (
    'id' => '23921',
    'deleted' => '0',
    'published' => NULL,
    'created' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'modified' => Cake\Chronos\Chronos::getTestNow()->toDateTimeString(),
    'created_by' => NULL,
    'modified_by' => NULL,
    'sortno' => NULL,
    'sortkey' => NULL,
    'propertytype' => 'personnames',
    'signature' => NULL,
    'file_name' => NULL,
    'properties_id' => NULL,
    'lemma' => 'Adamaro',
    'name' => 'Völschow, Adamoaro',
    'unit' => NULL,
    'comment' => 'nie geboren',
    'content' => NULL,
    'elements' => NULL,
    'keywords' => NULL,
    'source_from' => NULL,
    'ishidden' => NULL,
    'iscategory' => NULL,
    'norm_type' => 'doida',
    'norm_data' => '',
    'norm_iri' => NULL,
    'import_db' => '',
    'import_id' => '',
    'related_id' => NULL,
    'mergedto_id' => NULL,
    'splitfrom_id' => NULL,
    'parent_id' => NULL,
    'level' => '0',
    'lft' => '7',
    'rght' => '8',

  ),
);
