[PHP]
expose_php = Off
memory_limit = 1024M
max_execution_time = 600
max_input_vars = 10000
post_max_size = 512M
upload_max_filesize = 512M
date.timezone = Europe/Berlin

error_reporting = E_ALL & ~E_DEPRECATED
display_errors = Off
log_errors = On
error_log = /dev/stderr

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 30000
opcache.validate_timestamps = 0

[session]
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.gc_maxlifetime = 7800